### PR TITLE
Upgrade japicmp-maven-plugin

### PR DESCRIPTION
**Pull request by hmottestad**
This PR addresses GitHub issue: eclipse/rdf4j#1421 .

Briefly describe the changes proposed in this PR:

* upgraded  japicmp-maven-plugin
* 
*

### CODE REVIEW

**Comment by hmottestad** [comment]
@jeenbroekstra I upgrading this because the old version does not work with java 11, however the new one does. Does it require a CQ?

**Comment by barthanssens** [comment]
mvn clean install -DskipTests works on JDK11, still an issue when tests are enabled

**Comment by hmottestad** [comment]
@barthanssens should we just merge this anyway. As a start!

**Comment by barthanssens** [comment]
+1, we need to test it anyway :-)

**Pull request merged**
