### PR TITLE
GH-89 include JTS and use as default SpatialSupport

### PR DESCRIPTION
**Pull request by jeenbroekstra**
This PR addresses GitHub issue: #89 .

Briefly describe the changes proposed in this PR:

* bumped spatial4j to 0.7
* included jts 1.15.1
* refactored SpatialSupport and related classes to use full JTS functionality by default

### CODE REVIEW

**Comment by jeenbroekstra** [comment]
@pulquero I based some off this of your bitbucket project that demonstrates a SpatialAlgebra implementation using JTS, but updated to the latest spatial4j and jts APIs. Keen to hear what you think.

**Comment by jeenbroekstra** [comment]
There's three GeoSPARQL compliance tests failing, it looks like it has something to do with inclusion of "empty" points, but I can't immediately see what's wrong.

**Comment by pulquero** [comment]
Nice, I think the problem with the tests is to do with wkt serialization. An empty geometry is being written out as "GEOMETRYCOLLECTION ()"^^<http://www.opengis.net/ont/geosparql#wktLiteral> and not "GEOMETRYCOLLECTION EMPTY"^^<http://www.opengis.net/ont/geosparql#wktLiteral>. You probably need to modify toWKT() to something like if(!shape.isEmpty()) return wktWriter.toString(shape); else return "GEOMETRYCOLLECTION EMPTY";

**Comment by jeenbroekstra** [comment]
I've logged two issues for possible Spatial4J bugs related to this:

https://github.com/locationtech/spatial4j/issues/162
https://github.com/locationtech/spatial4j/issues/163

For now I've managed to implement workarounds that at least cover our test cases.

**Pull request merged**
