### PR TITLE
Feature/#743 add support for shacl

### PR DESCRIPTION
**Pull request by hmottestad**
### This is a PR to track the work on aligning the SHACL engine with the new repo layout, making tests, and adding support for optimised partial validation as well as maxCount and datatype validation.

This PR addresses GitHub issue: eclipse/rdf4j#743 .

Briefly describe the changes proposed in this PR:

* Add support for SHACL (small subset)
* Fix NotifyingSail for add-remove-add scenarios
*

### CODE REVIEW

**Comment by hmottestad** [comment]
@heshanjse I have moved your branch here, so that it can be merged in the correct place. I've started adding tests and fixing things so that I can implement support for validating only modified data. Your sign off footer seems too have been wrong for some reason, so I've fixed that in all your commits.

**Comment by hmottestad** [comment]
After a few days work the SHACL Sail now supports:

 - targetClass
 - path (single predicate)
 - minCount

The SHACL Sail will generate plans for validating the data so that:
 - only rules that need to run are run
 - plans only validate data that has changed
 - plans get data from changes first, and then supplements with data from the baseSail.

This means that if you have 500 000 000 triples and add 1 more triple. Then the SHACL Sail will only consider rules that could now be broken and generate plans for those, and those plans will only validate that 1 triple and pull any supplemental data from the 500 000 000 triples in the baseSail if needed.

**Comment by jeenbroekstra** [comment]
FWIW at some point we simply have to bite the bullet and just roll this out - how confident are you currently, @hmottestad, that this is now in a state that is useful to RDF4J users (even if we call it a beta/experimental feature)?

**Comment by hmottestad** [comment]
@jeenbroekstra

minCount, maxCount, simple property path and target class work fine. Performance for maxCount is still a bit low, but minCount is fast. 

We just went into production last week with our system, but I’m still not going to have much time for rdf4j in the next few weeks. Asked my boss for time to work on rdf4j, he was positive but not extatic. Also moving apartments, last few boxes now.

There are two other things I haven’t done. 1. correct indentation; 2. correct author and copyright notices. 

Also, I have a fix for a bug I found in the notifying sail implementation where it wouldn’t notify on changes correctly when adding, removing and re-adding a statement. Last add wasn’t reported.

**Comment by hmottestad** [comment]
@jamesrdf @jeenbroekstra 

I'm fairly happy to merge this in as experimental and work-in-progess.

Supported features:

 - Shapes
 - Shapes with target class
 - Single predicate paths
 - minCount
 - maxCount

Failed validation will throw an exception. There is some logging for showing the general cause of the validation failure, but it is very rudimentary. 

Travis is currently complaining about something completely different: 
```
Running org.eclipse.rdf4j.sail.nativerdf.NativeStoreConcurrencyTest
09:20:13.819 [main] INFO  executing two large concurrent transactions
09:20:18.751 [Thread-2] INFO  Uploaded 200000 statements
09:25:28.840 [main] INFO  Still waiting for transactions to commit
09:30:28.841 [main] INFO  Still waiting for transactions to commit


The job exceeded the maximum time limit for jobs, and has been terminated.
```
Not sure if this is my fault.

**Comment by hmottestad** [comment]
This is how you use the ShaclSail:

```
NotifyingSail baseSail = new MemoryStore();
SailRepository shaclRules = ... ;
SailRepository shaclSail = new SailRepository(new ShaclSail(baseSail, shaclRules));
shaclSail.initialize();
```

The SHACL rules can not be modified after initialization at the moment. It is possible to create a feature for rebuilding the AST (Abstract Syntax Tree), but there is no such feature at the moment.

**Pull request merged**
