### PR TITLE
eclipse/rdf4j#1117 shacl w3c tests

### PR DESCRIPTION
**Pull request by hmottestad**
This PR addresses GitHub issue: eclipse/rdf4j#1117  .

Briefly describe the changes proposed in this PR:

* added SHACL compliance tests files from w3c repo
* created (simple) code for running tests
* migrated our code to use sh:NodeShape (from sh:Shape), must be from before spec was finalized

### CODE REVIEW

**Comment by hmottestad** [comment]
This needs further discussion on what to do about the w3c files (intellectual property wise). Also, unimplemented features are currently failing the build.

**Comment by hmottestad** [comment]
add to whitelist

**Comment by hmottestad** [comment]
We are now up from 18 to 20 passing tests after the last fixes for sh:or.

**Comment by hmottestad** [comment]
We now have 24/98 passing.

Mind you nothing builds at the moment because of 3.0 snapshot on develop.

**Comment by hmottestad** [comment]
Synced with develop.

We are now at 13/98 passing.

**Comment by hmottestad** [comment]
24/98 now

**Comment by hmottestad** [comment]
25/98 noq

**Comment by hmottestad** [comment]
26/98 now

**Comment by hmottestad** [comment]
42/98 now

**Comment by hmottestad** [comment]
46/98 now

**Comment by hmottestad** [comment]
47/98 now

**Comment by hmottestad** [comment]
@rdf4j-bot run tests

**Comment by hmottestad** [comment]
48/98 now

**Comment by jeenbroekstra** [comment]
@hmottestad what do you want to do with this PR? It's grown a bit stale. If we are going to reintegrate to a single repo next week, we'll need this either merged, or dropped (and then later resubmitted?).

**Comment by hmottestad** [comment]
We could mark the test as @ignore and merge it. 

There is a competing implementation of these tests in the compliance test suite, but the way the tests are generated make them impossible to debug in IntelliJ. It’s got something to do with how the tests are generated at runtime from the turtle files. For this reason I prefer my approach.

**Comment by jeenbroekstra** [comment]
> We could mark the test as @ignore and merge it.

Works for me. Could you take care of this?

> There is a competing implementation of these tests in the compliance test suite, but the way the tests are generated make them impossible to debug in IntelliJ. It’s got something to do with how the tests are generated at runtime from the turtle files. For this reason I prefer my approach.

I understand the problem (I had similar issues in the past with the SPARQL compliance tests).  Just make sure that when you create a separate test that exactly duplicates one of the testsuite tests, for debugging purposes, you remove that test again once you're done debugging - otherwise it all becomes a bit messy :)

**Pull request merged**
