### PR TITLE
Issues/1375 bigger benchmark

### PR DESCRIPTION
**Pull request by hmottestad**
This PR addresses GitHub issue: eclipse/rdf4j#1375 .

Briefly describe the changes proposed in this PR:

* benchmark with big file
* 

Requires CQ.

### CODE REVIEW

**Comment by hmottestad** [comment]
CQ not sent yet. @jeenbroekstra @barthanssens I used (and modified) the turtle file that Bart mentioned from here: https://github.com/Fedict/dcat/tree/master/all

@barthanssens Can you clarify the license? The entire repo has "Creative Commons Zero v1.0 Universal", does this hold for the big file too?

**Comment by barthanssens** [comment]
I have to re-check, it is a reprocessing of metadata of several differentbportals and it _used_ to be that the medata of these portals was CC0, but some may have switched to a CC-BY(-ish) license :-(
  
(you can still use it for testing of course, but I'll have to ask the portal owners if they didn't specify the license in the original versions of theor metadata feeds)

**Comment by hmottestad** [comment]
CQ19489

**Comment by hmottestad** [comment]
http://dev.eclipse.org/ipzilla/show_bug.cgi?id=19489

**Comment by hmottestad** [comment]
Gotta love how they re-encode the re-encoded version of their lack of utf-8 support:

Screenshot 2019-04-03 at 20 00 19

**Comment by hmottestad** [comment]
CQ approved

**Comment by hmottestad** [comment]
apparently that was not CQ approved, but PMC approved, which is something different

**Pull request merged**
