### PR TITLE
Issues/1148 jdk11

### PR DESCRIPTION
**Pull request by hmottestad**
This PR addresses GitHub issue: eclipse/rdf4j#1148 .

Briefly describe the changes proposed in this PR:

* jaxb
* 
*

### CODE REVIEW

**Comment by hmottestad** [comment]
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/havardottestad/Documents/Programming/RDF4J/rdf4j-storage/compliance/sparql/target/rdf4j-server/WEB-INF/lib/logback-classic-1.1.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/havardottestad/.m2/repository/ch/qos/logback/logback-classic/1.1.11/logback-classic-1.1.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/Users/havardottestad/Documents/Programming/RDF4J/rdf4j-storage/compliance/sparql/target/rdf4j-server/WEB-INF/lib/spring-core-4.3.21.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
21:20:25.730 [main] WARN  Server reports problem: Handler dispatch failed; nested exception is java.lang.AbstractMethodError: Method org/eclipse/rdf4j/sail/memory/MemoryStoreConnection.pendingRemovals()Z is abstract

org.eclipse.rdf4j.repository.RepositoryException: Handler dispatch failed; nested exception is java.lang.AbstractMethodError: Method org/eclipse/rdf4j/sail/memory/MemoryStoreConnection.pendingRemovals()Z is abstract

	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.execute(SPARQLProtocolSession.java:1019)
	at org.eclipse.rdf4j.http.client.SPARQLProtocolSession.executeNoContent(SPARQLProtocolSession.java:978)
	at org.eclipse.rdf4j.http.client.RDF4JProtocolSession.upload(RDF4JProtocolSession.java:946)
	at org.eclipse.rdf4j.http.client.RDF4JProtocolSession.upload(RDF4JProtocolSession.java:770)
	at org.eclipse.rdf4j.http.client.RDF4JProtocolSession.upload(RDF4JProtocolSession.java:761)
	at org.eclipse.rdf4j.repository.http.HTTPRepositoryConnection.add(HTTPRepositoryConnection.java:427)
	at org.eclipse.rdf4j.query.parser.sparql.SPARQLServiceEvaluationTest.loadDataSet(SPARQLServiceEvaluationTest.java:194)
	at org.eclipse.rdf4j.query.parser.sparql.SPARQLServiceEvaluationTest.prepareTest(SPARQLServiceEvaluationTest.java:169)
	at org.eclipse.rdf4j.query.parser.sparql.SPARQLServiceEvaluationTest.testVariableNameHandling(SPARQLServiceEvaluationTest.java:254)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


```

**Comment by hmottestad** [comment]
@barthanssens what do you think? Do we need IP logs for the jakarta jaxb implementation?

**Comment by barthanssens** [comment]
> Now failing with this in SPARQLServiceEvaluationTest:
> 
> ```
> 21:20:25.730 [main] WARN  Server reports problem: Handler dispatch failed; nested exception is java.lang.AbstractMethodError: Method org/eclipse/rdf4j/sail/memory/MemoryStoreConnection.pendingRemovals()Z is abstract
> ```

I had a similar issue, but it disappeared after removing the local .m2 maven directory

**Comment by barthanssens** [comment]
> @barthanssens what do you think? Do we need IP logs for the jakarta jaxb implementation?

Our javax.xml.bind 2.3.x has been approved (CQ 20163)

I'm inclined to think we don't need a CQ for the glassfish jaxb runtime, since it's now an incubating Eclipse project, but I'll check anyway...

**Comment by hmottestad** [comment]
I think this is ready to merge now

**Comment by barthanssens** [comment]
I've created a CQ for the runtime just to be sure (CQ20291), other than that, thumbs up :-)

**Comment by hmottestad** [comment]
I swapped over to javax.xml.bind from Jakarta. So no CQ required.

**Comment by hmottestad** [comment]
I didn’t need the runtime. We might not need it in the other projects either.

**Pull request merged**
