### PR TITLE
#104 renamed Shape to NodeShape

### PR DESCRIPTION
**Pull request by hmottestad**
This PR addresses GitHub issue: #104 .

Briefly describe the changes proposed in this PR:

* renamed code from Shape to NodeShape
* filter subjects for NodeShape instead of Shape (not backwards compatible)
* update tests

### CODE REVIEW

**Comment by hmottestad** [comment]
Note that his change is not backwards compatible and will break current functionality for our users.

**Comment by jeenbroekstra** [comment]
add to whitelist

**Comment by hmottestad** [comment]
@jeenbroekstra did you disable Travis already? You mentioned a Hudson server, all I have access to is the Jenkins one that Eclipse runs and I can't see it in the checks here at the moment.

**Comment by jeenbroekstra** [comment]
Yes, Travis is disabled. We have set up Jenkins to build PRs, but it appears not to be set up correctly; it does verify PRs, but it doesn't show up as a status check, at least not in this repo. Bear with me, I can't configure this myself, I need to work via the eclipse webmaster.

**Comment by jeenbroekstra** [comment]
@hmottestad for example this particular PR was verified in this Jenkins build:

  https://ci.eclipse.org/rdf4j/job/rdf4j-storage-verify-pullrequest/4/

As you can see it reports several test failures. I'm looking into why this status isn't reported on the actual PR.

**Comment by hmottestad** [comment]
Do you reckon i could merge these changes? @jeenbroekstra

**Comment by jeenbroekstra** [comment]
Yeah go ahead :+1:

**Pull request merged**
